etl_eurostat_local:
	python main.py eurostat local raw eurostat --new-table

etl_usbls_local:
	python main.py usbls local CUUR0000SA0 1913 2023 raw usbls --new-table

etl_restcountries_local:
	python main.py restcountries local raw restcountries --new-table
